name: moop
channels:
  - rdkit
  - anaconda
  - chen
  - conda-forge
  - defaults
dependencies:
  - aniso8601=6.0.0
  - asn1crypto=0.24.0
  - attrs=19.1.0
  - blas=1.0
  - bzip2=1.0.6
  - ca-certificates=2019.1.23
  - cairo=1.14.12
  - cairocffi=0.9.0
  - certifi=2019.3.9
  - cffi=1.12.3
  - chardet=3.0.4
  - click=7.0
  - cryptography=2.6.1
  - cssselect2=0.2.1
  - defusedxml=0.5.0
  - flask=1.0.2
  - flask-restplus=0.11.0
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.56.2
  - icu=58.2
  - idna=2.8
  - intel-openmp=2019.3
  - itsdangerous=1.1.0
  - jinja2=2.10.1
  - joblib=0.13.2
  - jpeg=9b
  - jsonschema=3.0.1
  - krb5=1.16.1
  - libboost=1.67.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libpng=1.6.36
  - libpq=11.2
  - libtiff=4.0.10
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - markupsafe=1.1.1
  - mkl=2019.3
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - ncurses=6.1
  - numpy=1.16.3
  - numpy-base=1.16.3
  - olefile=0.46
  - openssl=1.1.1c
  - pandas=0.24.2
  - pcre=8.43
  - pillow=6.0.0
  - pip=19.1
  - pixman=0.38.0
  - postgresql=11.2
  - psycopg2=2.7.6.1
  - py-boost=1.67.0
  - pycparser=2.19
  - pymongo=3.7.2
  - pyopenssl=19.0.0
  - pyrsistent=0.14.11
  - pysocks=1.6.8
  - python=3.6.8
  - python-dateutil=2.8.0
  - pytz=2019.1
  - rdkit=2019.03.1.0
  - readline=7.0
  - requests=2.21.0
  - scikit-learn=0.21.1
  - scipy=1.2.1
  - setuptools=41.0.1
  - six=1.12.0
  - sqlite=3.27.2
  - tinycss2=0.6.1
  - tk=8.6.8
  - urllib3=1.24.2
  - webencodings=0.5.1
  - werkzeug=0.15.2
  - wheel=0.33.1
  - xlwt=1.3.0
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7

